apiVersion: batch/v1
kind: Job 
metadata:
  name: node-app-job 
spec:
  completions: 2
  template:
    spec:
      containers: 
      - name: node-app-job 
        image: alpine 
        command: ["echo", "test  app node"]
      restartPolicy: Never