apiVersion: batch/v1
kind: Job 
metadata:
  name: node-app-job 
spec:
  template:
    spec:
      containers: 
      - name: node-app-job 
        image: alpine 
        command: ["echo, testp app node"]
      restartPolicy: Never