###we know that all the intraction to your k8s cluster happen through api
apiVersion: v1
####pod is a generic term
#it will invoke the pod api which is like a wrapper to deploy our container workload
kind: Pod #kubernetes entity
metadata:
  name: sidecar-app #inside your k8s cluster we need to create a pod.  
spec: #inside my pod api i want to deploy a container
  volumes:
  - name: logs 
    emptyDir: {}
  containers: 
  - name: appcontainer
    image: alpine 
    command: ["/bin/bash"]
    args: ["-c,"while true; do date >> /var/log/app/log; sleep 5; done"]
    volumeMounts:
    - name: logs 
      mountPath: /var/log 
    
  - name: log-exporter-sidecar
    image: nginx 
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs 
      mountPath: /usr/share/nginx/html
