apiVersion: apiextensions.k8s.io/v1
 
kind: CustomResourceDefinition
 
metadata:
 
# Name of your CRD. Must match the spec block below, and be in the form: <plural>.<group>
 
name: routers.example.com
 
spec:
 
# Group name to use for REST API: /apis/<group>/<version>
 
group: example.com
 
names:
 
# Plural name to be used in the URL: /apis/<group>/<version>/<plural>
 
plural: routers
 
# Singular name to be used as an alias on the CLI and for display
 
singular: router
 
# Kind is normally the CamelCased singular type. Your resource manifests use this.
 
kind: Router
 
# ShortNames allow shorter string to match your resource on the CLI
 
shortNames:
 
- rt
 
# Scope can be either Namespaced or Cluster-wide
 
scope: Cluster
 
versions:
 
- name: v1
 
# Each version can be enabled/disabled by Served flag.
 
served: true
 
# One and only one version must be marked as the storage version.
 
storage: true
 
schema:
 
openAPIV3Schema:
 
type: object
 
properties:
 
spec:
 
type: object
 
properties:
 
dataCenter:
 
type: string
 
rack:
 
type: integer
 
type:
 
type: string
 
enum:
 
- f5
 
- virtual
 
required: ["dataCenter", "rack", "type"]
 
required: ["spec"]