apiVersion: v1 
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 10Gi #but this is an thin provisioing 
 
  accessModes:
    - ReadWriteOnce #readwritemany #read

  storageClassName: fistorage
  hostPath:
    path: /mnt/data